repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # use the latest stable version
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0  # use the version that matches your pyproject.toml
    hooks:
      - id: black
        language_version: python3.12  # or "python3.12" if needed

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # use the version that matches your pyproject.toml
    hooks:
      - id: flake8
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # use the version that matches your pyproject.toml
    hooks:
      - id: isort
        name: isort (pyproject.toml)
        language_version: python3.12
